#!/usr/bin/env python
import json
from pathlib import Path

PATH = Path("~/.config/obsidian/obsidian.json").expanduser()
if PATH.exists():
    with PATH.open() as f:
        data = json.load(f)
        if isinstance(data, dict) and "vaults" in data:
            vaults = data["vaults"]
            for i in vaults.values():
                i.pop("open", None)
    with PATH.open("w") as f:
        json.dump(data, f)
