{ ... }:
{
  imports = [
    ./alacritty
    ./android.nix
    ./audio
    ./cplay-ng.nix
    ./deadbeef.nix
    ./discord.nix
    ./firefox.nix
    ./gimp.nix
    ./git
    ./gnupg.nix
    ./inkscape.nix
    ./libreoffice.nix
    ./macchina
    ./mc
    ./mpv
    ./nushell
    ./obsidian.nix
    ./qview
    ./slack.nix
    ./steam.nix
    ./sublime
    ./syncplay.nix
    ./telegram.nix
    ./transmission.nix
    ./zathura
  ];
}
