spacing = 2
padding = 0
hide_ascii = true
separator = ">"
key_color = "Cyan"
separator_color = "White"

[palette]
type = "Full"
visible = false

[bar]
glyph = "ß‹"
symbol_open = '['
symbol_close = ']'
hide_delimiters = true
visible = true

[box]
border = "plain"
visible = true

[box.inner_margin]
x = 0
y = 0

[randomize]
key_color = false
separator_color = false

[keys]
host = "Host"
kernel = "Kernel"
cpu = "CPU"
cpu_load = "CPU Load"
gpu = "GPU"
memory = "Memory"
disk_space = "Disk Space"
backlight = "Brightness"
battery = "Battery"
uptime = "Uptime"
