# Toggle between displaying the current shell or your user's default one.
current_shell = true

# Lengthen kernel output
long_kernel = true

# Lengthen shell output
long_shell = false

# Lengthen uptime output
long_uptime = false

# Toggle between displaying the number of physical or logical cores of your processor.
physical_cores = true

# Themes need to be placed in "$XDG_CONFIG_DIR/macchina/themes" beforehand.
theme = "default"

# Displays only the specified readouts.
show = [
    "Battery",
    "Backlight",
    "Host",
    "Kernel",
    "Memory",
    "Processor",
    "ProcessorLoad",
    "Uptime",
]
