name: "CI"
on:
  workflow_dispatch:
  schedule:
    - cron: '00 01 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Update
        run: nix flake update
      - name: Build
        run: for host in legion yoga; do nix build .#nixosConfigurations."$host".config.system.build.toplevel; done
