name: "CI"
on:
  workflow_dispatch:
  schedule:
    - cron: '00 01 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: true
          remove-cached-tools: true
          remove-docker-images: true
          remove-dotnet: true
          remove-codeql: true
          remove-haskell: true
          remove-large-packages: true
          remove-swapfile: false
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Update
        run: nix flake update
      - name: Build
        run: for host in legion yoga; do nix build .#nixosConfigurations."$host".config.system.build.toplevel; done
